### ISSUE TITLE
Cannot log in, cannot request password reset.

### ISSUE THREAD

**Issue by Nordgaren** [CAPESandbox/community#351]
Hello!

Sorry if this is the wrong place, but this is the only place I could find to contact you.

I registered my account a while back, but I was on a VPN, and I think that got me flagged, as it said I needed to wait for the system admin to review my account or something. I couldn't find where to contact you (and I didn't think this would be the place to do so), and I never got anything back from you guys, so I just moved on.

Recently, I wanted to try CAPE out to look at some API calls, so I tried to reset my password, hoping that it was all sorted out and my account had been reviewed, but I get no password recovery e-mail

My e-mail is `nordgarentv@gmail,com`, and my username is `nordgaren`.

Edit: I finally got the e-mail, but it says there is no record of my account, but if I try to sign up again, it says a user is already registered at that address and that my username is already taken.

Thank you!
Nordgaren.

**Comment by kevoreilly** [comment]
Try now, let me know if it works 👍

**Comment by Nordgaren** [comment]
It works! Thank you so much!
