### ISSUE TITLE
Request: Sync `CAPE-parsers` dependency with package release

### ISSUE THREAD

**Issue by cccs-rs** [CAPESandbox/community#475]
Would it be possible to update the `CAPE-parsers` dependency in the pyproject.toml to be in-sync with the releases from https://github.com/CAPESandbox/CAPE-parsers?

**Comment by doomedraven** [comment]
they are in capev2 repo, bumped there

**Comment by cccs-rs** [comment]
Right, it seems to update the value in the requirements.txt in the CAPEv2 project but would it be possible to do the same or similar in the community project since we have scripts looking at this particular repo for leveraging the extractors?

**Comment by cccs-rs** [comment]
Haha no worries, this can definitely wait but yup, that's the request 😁

**Comment by doomedraven** [comment]
wouldn't it be just better to use latest version in script? i mean upgrade to latest, i have in ToDo to check if there is way to propagate version between repos, but the idea is to just bump to latest

**Comment by cccs-rs** [comment]
Well Assemblyline uses the commit for caching to determine whether or not if the system needs to clone the repo to drag in new signatures. This is something I can address on my side as a configuration, so it may not be as necessary to address this request:
![image](https://github.com/user-attachments/assets/9d0e4a00-8b6d-43cb-87c2-0edab899b2f4)

Thanks for your consideration though, as always 😁

**Comment by doomedraven** [comment]
if you using commit, wouldn't it be easier for you to you check what is the latest commit is?

**Comment by cccs-rs** [comment]
Correct, that is what we currently do but since this repo doesn't change that often in sync with changes with the CAPE-parsers repo, then the system thinks there's no reason to pull in changes again.

**Comment by cccs-rs** [comment]
It could but adding that configuration in our system to ignore caching for a particular source would work for us because there are other reasons why you might want to invalidate a cache (ie. a bug in the importer code which lead to missing signatures/extractors). Otherwise users at the moment would have to clear the cache key from Redis directly, which is probably not the best user experience 😅

**Comment by doomedraven** [comment]
ok iwill try to see how to push update to community/capev2 when new release is done, but it will take some time as i just came from PTO and have a lot of stuff todo, so in case if you aware how to push it to remote repo, let me know

**Comment by doomedraven** [comment]
i guess a github action with cron to check it once per day would work right? https://github.com/actinia-org/actinia-core/blob/main/.github/workflows/update-version.yml
https://github.com/actinia-org/actinia-core/blob/main/.github/workflows/update-version.yml￼
actinia-core/.github/workflows/update-version.yml at main · actinia-org/actinia-core
github.com
